### ISSUE TITLE
Multiple notations on a single property 

### ISSUE THREAD

**Issue by imperu** [JaroslawWaliszko/ExpressiveAnnotations#47]
Hey,
First off, I've been looking a lot for something like Expressive-Annotations and it works great!

I've done this (a single line):
```
[AssertThat(@"(nDisplayMode!=3 && nAThreshold<=95 && nAThreshold>=5) 
              || (nDisplayMode==3 && (nAThreshold<=95 && nAThreshold>=5 || nAThreshold<=-5 && nAThreshold>=-95))", 
            ErrorMessage = "A Threshold is out of range")]       
```
and it's working just fine, but than i wanted to be a little more specific with the error message, so I've done this (4 lines):
```
[RequiredIf("nDisplayMode==3")]
[AssertThat("((nAThreshold>=5 && nAThreshold<=95) || (nAThreshold>=-95 && nAThreshold<=-5))",
            ErrorMessage = "A-Threshold is out of range (-95)-(-5) or (5-95)")]
[RequiredIf("nDisplayMode!=3")]
[AssertThat("nAThreshold>=5 && nAThreshold<=95", 
            ErrorMessage = "A-Threshold is out of range (5-95)")]
```
but only the first 2 lines of RequiredIf-AssertThat seem to work. Is there any other way for me to do this a bit more specific? 

thanks,

**Comment by JaroslawWaliszko** [comment]
Hi,
Your first case is fine. One thing can be improved though - the error message should be more meaningfull of what "out-of-range" means. It should be extended to provide sufficient description what ranges are correct for what display modes.

On the other hand, you can decorate one field with multiple annotations, but in your second case there is some inconsistency in my opinion. The `RequiredIf` attributes are mutually exclusive here. What I mean by that statement is, if one attribute is satisfied (`!= 3`), the second one is not (`== 3`), and vice-versa. In other words, it seems that `nTreshold` should be always provided, no matter what `nDisplayMode` value is. Because of that, `nTreshold` shouldn't be even declared as `nullable` (if it is already declared like that - I don't see how it looks like from your snippet though but usage of `RequiredIf` rather implies that). 

If `nTreshold` value should always be provided, you can differentiate the ranges based on the `nDisplayMode` value using `AssertThat` only, just like you've done in the first case, but with more descriptive error message. Alternatively you can mimic the complex expression, by breaking it apart - but it is a bit tricky. The logic here is to provide the complementary **or-statement** for each attribute, mainly:
```
[AssertThat("(nDisplayMode==3 && ((nTreshold>=5 && nTreshold<=95) || (nTreshold>=-95 && nTreshold<=-5))) || nDisplayMode!=3",
            ErrorMessage = "Treshold is out of range [-95,-5] or [5,95] for display mode equal to 3")]
[AssertThat("(nDisplayMode!=3 && nTreshold>=5 && nTreshold<=95) || nDisplayMode==3",
            ErrorMessage = "Treshold is out of range [5,95] for display mode other than 3")]
public int nTreshold { get; set; }
```

Regards

**Comment by imperu** [comment]
Hi,
The "out-of-range" is the main reason for this post. Thanks, i believe that now i get the "flow" of the exception idea and the reason why i can only see the first validation rule fired.

However, now i get a different kind of error while calling the "SaveChanges" method.
An exception is thrown as follows:

System.Data.Entity.Validation.DbUnexpectedValidationException: An unexpected exception was thrown during validation of 'A Threshold (%)' when invoking ExpressiveAnnotations.Attributes.AssertThatAttribute.IsValid. See the inner exception for details. ---> System.ComponentModel.DataAnnotations.ValidationException: AssertThatAttribute: validation applied to AllParamSetup.nAThreshold field failed. ---> System.InvalidOperationException: Parse error on line 1, column 2:
... nDisplayMode==3 && ((nAThreshold>=5 && nAThreshold<=95) || (nAThreshold>=-95 && nAThreshold<=-5)) ) ...
    ^--- Only public properties, constants and enums are accepted. Identifier 'nDisplayMode' not known.
   at ExpressiveAnnotations.Analysis.Parser.Parse(Type context, String expression)
   at ExpressiveAnnotations.Attributes.ExpressiveAttribute.Compile(Type validationContextType, Boolean force)
   at ExpressiveAnnotations.Attributes.AssertThatAttribute.IsValidInternal(Object value, ValidationContext validationContext)
   at ExpressiveAnnotations.Attributes.ExpressiveAttribute.IsValid(Object value, ValidationContext validationContext)
   --- End of inner exception stack trace ---
   at ExpressiveAnnotations.Attributes.ExpressiveAttribute.IsValid(Object value, ValidationContext validationContext)
   at System.ComponentModel.DataAnnotations.ValidationAttribute.GetValidationResult(Object value, ValidationContext validationContext)
   at System.Data.Entity.Internal.Validation.ValidationAttributeValidator.Validate(EntityValidationContext entityValidationContext, InternalMemberEntry property)
   --- End of inner exception stack trace ---
   at System.Data.Entity.Internal.Validation.ValidationAttributeValidator.Validate(EntityValidationContext entityValidationContext, InternalMemberEntry property)
   at System.Data.Entity.Internal.Validation.PropertyValidator.Validate(EntityValidationContext entityValidationContext, InternalMemberEntry property)
   at System.Data.Entity.Internal.Validation.ComplexTypeValidator.ValidateProperties(EntityValidationContext entityValidationContext, InternalPropertyEntry parentProperty, List`1 validationErrors)
   at System.Data.Entity.Internal.Validation.TypeValidator.Validate(EntityValidationContext entityValidationContext, InternalPropertyEntry property)
   at System.Data.Entity.Internal.Validation.ComplexPropertyValidator.Validate(EntityValidationContext entityValidationContext, InternalMemberEntry property)
   at System.Data.Entity.Internal.Validation.EntityValidator.ValidateProperties(EntityValidationContext entityValidationContext, InternalPropertyEntry parentProperty, List`1 validationErrors)
   at System.Data.Entity.Internal.Validation.TypeValidator.Validate(EntityValidationContext entityValidationContext, InternalPropertyEntry property)
   at System.Data.Entity.Internal.InternalEntityEntry.GetValidationResult(IDictionary`2 items)
   at System.Data.Entity.DbContext.ValidateEntity(DbEntityEntry entityEntry, IDictionary`2 items)
   at System.Data.Entity.DbContext.GetValidationErrors()
   at System.Data.Entity.Internal.InternalContext.SaveChanges()


The data annotation on the property is:

[Display(Name = "A Threshold (%)")]
        [Required(ErrorMessage="A-Threshold is required")]
        [AssertThat(@"(nDisplayMode==3 && ((nAThreshold>=5 && nAThreshold<=95) || (nAThreshold>=-95 && nAThreshold<=-5)) ) 
        || nDisplayMode!=3", ErrorMessage = "A Treshold is out of range [-95,-5] or [5,95]")]
        [AssertThat(@"(nDisplayMode!=3 && nATreshold>=5 && nATreshold<=95) 
        || nDisplayMode==3", ErrorMessage = "Treshold is out of range [5,95]")] 
        public int nAThreshold      { get; set; }

Of course that nDisplayMode exists and not null and without this annotation the data is accepted to the DB.
I've also tried to create other annotations with EA and the result is the same. 

I have no idea why it works on the client-side with exist data but can't handle the "savechanges" to the DB method. Any clues?

**Comment by JaroslawWaliszko** [comment]
Hi, part of the exception says:

> System.InvalidOperationException: Parse error on line 1, column 2:
... nDisplayMode==3 && ((nAThreshold>=5 && nAThreshold<=95) || (nAThreshold>=-95 && nAThreshold<=-5)) ) ...
^--- Only public properties, constants and enums are accepted. Identifier 'nDisplayMode' not known.

Is that `nDisplayMode` member declared as a **public property**? If not, it should be declared like that since currently EA implementation supports only public properties, constants and enums.

**Comment by imperu** [comment]
Yes, nDisplayMode is defined public just like nAThreshold. I thought that it might be related to something with the validation process, but i don't know what is so special about "savechanges". 
I will try to debug this issue tomorrow with the latest release.

**Comment by JaroslawWaliszko** [comment]
Ok. When you select *go to implementation* or *go to declaration* of `AssertThat` attribute, its sources downloading process should be triggered and finally stored in your temporary location, e.g.

![image](https://cloud.githubusercontent.com/assets/1596462/6225822/9127837e-b68f-11e4-82b1-1d769adcb64d.png)

The starting point for the debugger should be then inserted inside this validation method:

![image](https://cloud.githubusercontent.com/assets/1596462/6225836/a94bb66e-b68f-11e4-8688-8b4c37ff96b9.png)
